### ISSUE TITLE
Sprint 5

### ISSUE THREAD

**Issue by taoholl** [beta-mtn/web-app#13]
Team met on Tuesday 12th and did an overview of tasks for each person. 

Tao: create detailed wire frame to be done on Monday 19.
Nasrin: Create design assets for wireframes to be completed by Wednesday 21
Maja: start code on mobile wireframes and sketch out desktop wireframe for class on Monday 26.

**Comment by taoholl** [comment]
Monday 26 Review: 

Wire frames **completed**
Design for wireframe **completed**
Coding **not completed,** Wire frame for desktop completed

Comment: Coding was not completed this week and designed wire frames were not competed until Sunday the 25th. The tasks were set out on the Tuesday before break but the team did not stay in contact during the break. Wireframes were given at the correct time but I, as project lead, did not check in with the rest of the group resulting in work was not submitted on time. This is an issue because our group is already behind, I take full responsibility as team lead for not staying on top of my group.

**Comment by majabbergstrom** [comment]
Week 5 Sprint Review
For this week I was assigned the tasks of starting code for mobile app screen and making wireframes for desktop screens. During the week I fell ill and was only able to complete the wireframes. The design assets which were supposed to be handed off to me on Wednesday weren't sent until Saturday which also hindered the progress on coding. With this we are behind on coding and will have to work hard to make up the lost time. 
This past sprint had a lack of communication and time management between group members which will need to be resolved in order for the project to be completed by the deadline

**Comment by Nasrine** [comment]
last week I did the designing for the wireframe using the given brand colours. I did the icons two weeks ago but since we changed from calendar to planner, I am going to make new icons for the planner. This week I am going to make them and make them in SVG ready for coding.
